name: GPS
on:
  workflow_dispatch: 
  schedule:
    - cron: '25 0 * * 6'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  
      - name: Execute Python dependency
        run: |
          python -m pip uninstall -r requirement23.txt &&
          python -m pip cache purge &&
          python -m pip install --upgrade pip setuptools &&
          python -m pip install -r requirement23.txt
    
      - name: Generate PDF
        env:
          AK: ${{ secrets.GEMINI_API }}
        run: 
          python Beta_d_n.py
