name: LSTM
on:
  workflow_dispatch:

jobs:
  upload-plot:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - os: macos-latest
            gpu: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  
      - name: Execute Python dependency
        run: |
         python -m pip uninstall -r req.txt &&
         python -m pip cache purge &&
         python -m pip install --upgrade pip setuptools &&
         python -m pip install -r lstmreq.txt
         python -m pip install psutil gpustat
    
      - name: Monitor GPU usage
        run: |
          python
          import gpustat
          import time
          while True:
            gpu_usage = gpustat.new_query().json['gpus'][0]['utilization']
            print(f"GPU usage: {gpu_usage}%")
            time.sleep(1)
      
      - name: Generate PDF
        run: 
          python test.py
