name: combined
on:
  workflow_dispatch:

jobs:
  upload-plot:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - os: macos-latest
            gpu: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set environment variables
        id: set_env_vars
        run: |
         if [ -f "stocks.txt" ]; then
          echo "TS=$(cat stocks.txt)" >> $GITHUB_ENV
         else
          echo "File stocks.txt not found."
          exit 1
         fi
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  
      - name: Execute Python dependency
        run: |
         python -m pip uninstall -r requirements2.txt &&
         python -m pip cache purge &&
         python -m pip install --upgrade pip setuptools &&
         python -m pip install -r requirements2.txt
    
      - name: Generate PDF
        env:
          PWS: ${{ secrets.M_P }} 
          TS: ${{ env.TS }}
          AK: ${{ secrets.GEMINI_API }}
          RE: ${{ secrets.RE_EMAIL }}
          SE: ${{ secrets.S_EMAIL }}
        run: 
          python nt.py
