name: NSP
on:
  workflow_dispatch: 
  schedule:
    - cron: '25 0 * * 6'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set environment variables
        id: set_env_vars
        run: |
         if [ -f "stocks.txt" ]; then
          echo "TS=$(cat stocks.txt)" >> $GITHUB_ENV
         else
          echo "File stocks.txt not found."
          exit 1
         fi

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  
      - name: Execute Python dependency
        run: |
          python -m pip uninstall -r rnsp.txt &&
          python -m pip cache purge &&
          python -m pip install --upgrade pip setuptools &&
          python -m pip install -r rnsp.txt
    
      - name: Generate PDF
        env:
          PASSWORD: ${{ secrets.M_P }} 
          TS: ${{ env.TS }}
          AK: ${{ secrets.GEMINI_API }}
          RE: ${{ secrets.R_EML }}
          SE: ${{ secrets.S_EMAIL }}
          MGD: ${{ secrets.MGD }}
          MGA: ${{ secrets.MGA }}
          GAS: ${{ secrets.GAS }}
        run: 
          python nsp.py
