name: generate file
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set environment variables
        id: set_env_vars
        run: |
         if [ -f "stocks.txt" ]; then
          echo "TS=$(cat stocks.txt)" >> $GITHUB_ENV
         else
          echo "File stocks.txt not found."
          exit 1
         fi

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  
      - name: Execute Python dependency
        run: |
         python -m pip uninstall -r requirementts2.txt &&
         python -m pip cache purge &&
         python -m pip install --upgrade pip setuptools &&
         python -m pip install -r requirementts2.txt
    
      - name: Generate PDF
        env:
          TS: ${{ env.TS }}
          AK: ${{ secrets.GEMINI_API }}
        run: 
          python new_stock_pred.py

      - name: Configure Git
        run: |
          git config --global user.name "sandeephallimane"
          git config --global user.email "hssandp@gmail.com"

      - name: Pull latest changes
        run: git pull --rebase origin main

      - name: Commit PDF file
        run: |
          git add stocks.txt
          git commit -m "Add data.txt" || echo "Nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_REPO_TOKEN }}
