name: update table
on:
  workflow_dispatch:

jobs:
  upload-plot:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - os: macos-latest
            gpu: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  
      
      - name: Execute Python dependency
        run: |
         python -m pip uninstall -r requirements2.txt &&
         python -m pip cache purge &&
         python -m pip install --upgrade pip setuptools &&
         python -m pip install -r requirements2.txt 
    
      - name: Generate PDF
        run: 
          python updtab.py
          echo "::set-output name=a::$a"
          echo "::set-output name=b::$b"

      - name: Configure Git
        run: |
          git config --global user.name "sandeephallimane"
          git config --global user.email "hssandp@gmail.com"

      - name: Pull latest changes
        run: |
          set -o errexit  # Exit immediately if a command exits with a non-zero status
          git stash || echo "No local changes to stash"
          git pull --rebase origin main
          if git stash list | grep -q "stash@{0}"; then
            git stash pop || echo "No stash entries found"
          else
            echo "No stash entries to pop"
          fi
          shell: /bin/bash

      - name: Commit PDF file
        run: |
          git add upddata.txt
          git commit -m "Add upddata.txt" || echo "Nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_REPO_TOKEN }}

      - name: Retrigger workflow
        run: |
         sleep 300 # wait for 5 minutes
         if [ $a -gt $b ]; then
           curl -X POST \
           https://api.github.com/repos/sandeephallimane/Shs_stocks/actions/workflows/111935311/dispatches \
           -H 'Authorization: Bearer ${{ secrets.MY_REPO_TOKEN }}' \
           -H 'Content-Type: application/json' \
           -d '{"inputs": {} }'
         fi
